package com.p683ss.android.ttve.monitor;

import java.util.HashSet;
import java.util.Set;

/* renamed from: com.ss.android.ttve.monitor.i */
public final class C20117i {

    /* renamed from: a */
    private static final Set<String> f55328a = new HashSet();

    /* renamed from: b */
    private static final Set<String> f55329b = new HashSet();

    /* renamed from: c */
    private static final Set<String> f55330c = new HashSet();

    /* renamed from: d */
    private static final Set<String> f55331d = new HashSet();

    static {
        f55330c.add("te_preview_camera_resolution");
        f55329b.add("te_preview_preview_frame_rate");
        f55329b.add("te_preview_camera_zoom");
        f55328a.add("te_record_camera_direction");
        f55328a.add("te_record_camera_type");
        f55328a.add("te_record_switch_camera_time");
        f55329b.add("te_record_camera_frame_rate");
        f55328a.add("te_record_camera_size");
        f55328a.add("te_record_camera_stabilization");
        f55328a.add("te_record_camera_max_fps");
        f55328a.add("te_record_camera_hardware_level");
        f55328a.add("te_record_camera_open_cost");
        f55328a.add("te_record_camera_open_ret");
        f55328a.add("te_record_camera_preview_first_frame_cost");
        f55328a.add("te_record_camera_err_ret");
        f55330c.add("te_record_camera_open_info");
        f55328a.add("te_record_start_preview_ret");
        f55328a.add("te_record_preview_init_ret");
        f55328a.add("te_record_start_record_ret");
        f55328a.add("te_record_hard_encode_init_ret");
        f55328a.add("te_record_audio_start_record_ret");
        f55328a.add("te_record_audio_start_play_ret");
        f55328a.add("te_record_concat_ret");
        f55328a.add("te_record_concat_time");
        f55328a.add("te_record_preview_init_time");
        f55328a.add("te_record_preview_destroy_time");
        f55329b.add("te_record_hard_encode_init_time");
        f55329b.add("te_record_hard_encode_destroy_time");
        f55328a.add("te_record_audio_start_record_time");
        f55328a.add("te_record_audio_stop_record_time");
        f55328a.add("te_record_audio_first_frame");
        f55330c.add("te_record_audio_play_time_strs");
        f55330c.add("te_record_compose_vid");
        f55328a.add("te_preview_first_frame_render_time");
        f55330c.add("te_preview_video_preview_resolution");
        f55329b.add("te_preview_preview2_frame_rate");
        f55329b.add("te_preview_first_frame_screen_time");
        f55329b.add("te_preview_switch_camera_screen_time");
        f55328a.add("te_record_beauty_type");
        f55329b.add("te_record_smooth_intensity");
        f55329b.add("te_record_white_intensity");
        f55330c.add("te_record_filter_id1");
        f55330c.add("te_record_filter_id2");
        f55330c.add("te_record_sticker_id");
        f55329b.add("te_record_eye_intensity");
        f55329b.add("te_record_cheek_intensity");
        f55328a.add("te_record_lab_algorithm");
        f55328a.add("te_record_extract_frame_num");
        f55330c.add("te_record_resolution");
        f55330c.add("te_record_video_encode_type");
        f55328a.add("te_record_video_encode_mode");
        f55328a.add("te_record_audio_encode_mode");
        f55329b.add("te_record_video_frame_encode_time");
        f55328a.add("te_record_video_encode_gop");
        f55329b.add("te_record_frame_rate");
        f55329b.add("te_record_start_time");
        f55329b.add("te_record_stop_time");
        f55329b.add("te_record_render_average_time");
        f55328a.add("te_record_lag_max_num");
        f55328a.add("te_record_lag_count");
        f55328a.add("te_mediacodec_profile");
        f55328a.add("te_record_mediacodec_rate_control");
        f55328a.add("te_record_type");
        f55329b.add("te_record_speed");
        f55329b.add("te_record_export_time");
        f55329b.add("te_record_segment_time");
        f55328a.add("te_record_err_code");
        f55330c.add("te_record_video_soft_encode_acc_eglimage");
        f55328a.add("te_record_video_use_eglimage");
        f55328a.add("te_record_audio_latency");
        f55329b.add("te_record_camera_sharpness");
        f55329b.add("te_record_camera_sharpness_difference");
        f55331d.add("te_sensor_type_gyroscope_exist");
        f55331d.add("te_sensor_type_game_rotation_vector_exist");
        f55331d.add("te_sensor_type_rotation_vector_exist");
        f55331d.add("te_sensor_type_gravity_exist");
        f55331d.add("te_sensor_type_accelerometer_exist");
        f55330c.add("te_sensor_type_gyroscope_name");
        f55330c.add("te_sensor_type_game_rotation_vector_name");
        f55330c.add("te_sensor_type_rotation_vector_name");
        f55330c.add("te_sensor_type_gravity_name");
        f55330c.add("te_sensor_type_accelerometer_name");
        f55328a.add("te_edit_first_frame_time");
        f55328a.add("te_edit_reverse_time");
        f55329b.add("te_edit_video_decode_average_time");
        f55328a.add("te_edit_video_decode_mode");
        f55329b.add("te_edit_audio_decode_average_time");
        f55328a.add("te_edit_audio_decode_mode");
        f55328a.add("te_edit_err_code");
        f55328a.add("te_edit_import_generate_thumbnail_time");
        f55330c.add("te_edit_thumbnail_resolution");
        f55330c.add("te_composition_resolution");
        f55329b.add("te_composition_fps");
        f55329b.add("te_composition_bit_rate");
        f55329b.add("te_composition_file_duration");
        f55329b.add("te_composition_file_size");
        f55328a.add("te_composition_time");
        f55329b.add("te_composition_video_encode_time");
        f55329b.add("te_composition_audio_encode_time");
        f55329b.add("te_composition_video_decode_time");
        f55329b.add("te_composition_audio_decode_time");
        f55328a.add("te_composition_video_encode_mode");
        f55328a.add("te_composition_video_decode_mode");
        f55328a.add("te_composition_audio_encode_mode");
        f55328a.add("te_composition_audio_decode_mode");
        f55328a.add("te_composition_page_mode");
        f55328a.add("te_composition_effect_add");
        f55328a.add("te_composition_info_sticker_add");
        f55330c.add("te_composition_effect_json");
        f55330c.add("te_composition_info_sticker_json");
        f55328a.add("te_composition_text_add");
        f55328a.add("te_composition_brush_add");
        f55330c.add("te_composition_filter_id");
        f55328a.add("te_composition_watermark_add");
        f55328a.add("te_composition_end_watermark_add");
        f55328a.add("te_composition_time_filter_type");
        f55328a.add("te_composition_err_code");
        f55328a.add("te_composition_video_sw_crf");
        f55328a.add("te_composition_video_sw_maxrate");
        f55328a.add("te_composition_video_sw_preset");
        f55328a.add("te_composition_video_gop");
        f55328a.add("te_composition_tran_type");
        f55329b.add("te_edit_playback_fps");
        f55330c.add("te_record_resolution");
        f55330c.add("te_record_video_encode_type");
        f55328a.add("te_record_video_encode_mode");
        f55328a.add("te_record_audio_encode_mode");
        f55329b.add("te_record_frame_rate");
        f55329b.add("te_record_video_frame_encode_time");
        f55329b.add("te_record_start_time");
        f55329b.add("te_record_stop_time");
        f55328a.add("te_record_camera_type");
        f55329b.add("te_record_switch_camera_time");
        f55329b.add("te_record_render_average_time");
        f55330c.add("te_record_video_preview_resolution");
        f55329b.add("te_record_preview_frame_rate");
        f55329b.add("te_record_camera_frame_rate");
        f55329b.add("te_record_concat_time");
        f55328a.add("te_record_frame_cnt_bef_enq");
        f55328a.add("te_record_frame_cnt_aft_enq");
        f55328a.add("te_record_frame_cnt_bef_enc");
        f55328a.add("te_record_frame_cnt_aft_wrt");
        f55329b.add("te_video_decode_average_time");
        f55329b.add("te_audio_decode_average_time");
        f55328a.add("te_video_decode_mode");
        f55328a.add("te_audio_decode_mode");
        f55329b.add("te_editor_drop_frame_rate");
        f55329b.add("te_editor_preview_frame_rate");
        f55328a.add("te_editor_skip_processor");
        f55330c.add("te_composition_resolution");
        f55329b.add("te_composition_fps");
        f55329b.add("te_composition_bit_rate");
        f55329b.add("te_composition_file_duration");
        f55329b.add("te_composition_file_size");
        f55329b.add("te_composition_time");
        f55329b.add("te_composition_video_encode_time");
        f55329b.add("te_composition_audio_encode_time");
        f55329b.add("te_composition_video_decode_time");
        f55329b.add("te_composition_audio_decode_time");
        f55328a.add("te_composition_video_encode_mode");
        f55328a.add("te_composition_video_decode_mode");
        f55328a.add("te_composition_audio_encode_mode");
        f55328a.add("te_composition_audio_decode_mode");
        f55328a.add("te_composition_page_mode");
        f55330c.add("te_import_source_file_resolution");
        f55330c.add("te_import_crop_file_resolution");
        f55329b.add("te_import_generate_thumbnail_time");
        f55329b.add("te_import_crop_time");
        f55329b.add("te_import_crop_file_duration");
        f55329b.add("te_import_source_file_bitrate");
        f55329b.add("te_import_crop_file_bitrate");
        f55329b.add("te_import_source_file_duration");
        f55328a.add("te_composition_video_sw_crf");
        f55328a.add("te_composition_video_sw_maxrate");
        f55328a.add("te_composition_video_sw_preset");
        f55328a.add("te_composition_video_gop");
        f55328a.add("completed");
        f55330c.add("iesve_record_resolution");
        f55330c.add("iesve_record_video_encode_type");
        f55328a.add("iesve_record_video_encode_mode");
        f55328a.add("iesve_record_audio_encode_mode");
        f55329b.add("iesve_record_frame_rate");
        f55329b.add("iesve_record_video_frame_encode_time");
        f55329b.add("iesve_record_start_time");
        f55329b.add("iesve_record_stop_time");
        f55328a.add("iesve_record_camera_type");
        f55328a.add("iesve_record_camera_hw_level");
        f55329b.add("iesve_record_switch_camera_time");
        f55329b.add("iesve_record_render_average_time");
        f55330c.add("iesve_record_video_preview_resolution");
        f55329b.add("iesve_record_preview_frame_rate");
        f55329b.add("iesve_record_camera_frame_rate");
        f55329b.add("iesve_record_concat_time");
        f55328a.add("iesve_record_mediacodec_profile");
        f55328a.add("iesve_use_new_record");
        f55329b.add("iesve_video_decode_average_time");
        f55329b.add("iesve_audio_decode_average_time");
        f55328a.add("iesve_video_decode_mode");
        f55328a.add("iesve_audio_decode_mode");
        f55329b.add("iesve_seek_cost_ms");
        f55330c.add("iesve_composition_resolution");
        f55329b.add("iesve_composition_fps");
        f55329b.add("iesve_composition_bit_rate");
        f55329b.add("iesve_composition_file_duration");
        f55329b.add("iesve_composition_file_size");
        f55329b.add("iesve_composition_time");
        f55329b.add("iesve_composition_video_encode_time");
        f55329b.add("iesve_composition_audio_encode_time");
        f55329b.add("iesve_composition_video_decode_time");
        f55329b.add("iesve_composition_audio_decode_time");
        f55328a.add("iesve_composition_video_encode_mode");
        f55328a.add("iesve_composition_video_decode_mode");
        f55328a.add("iesve_composition_audio_encode_mode");
        f55328a.add("iesve_composition_audio_decode_mode");
        f55330c.add("iesve_import_source_file_resolution");
        f55330c.add("iesve_import_crop_file_resolution");
        f55329b.add("iesve_import_generate_thumbnail_time");
        f55329b.add("iesve_import_crop_time");
        f55329b.add("iesve_import_crop_file_duration");
        f55329b.add("iesve_import_source_file_bitrate");
        f55329b.add("iesve_import_crop_file_bitrate");
        f55329b.add("iesve_import_source_file_duration");
        f55328a.add("completed");
        f55328a.add("iesve_processor_frame_count_drc");
        f55328a.add("iesve_processor_sample_size_drc");
        f55328a.add("iesve_processor_total_process_cost_drc");
        f55328a.add("iesve_processor_effect_process_cost_drc");
        f55328a.add("iesve_processor_frame_count_cleaner");
        f55328a.add("iesve_processor_sample_size_cleaner");
        f55328a.add("iesve_processor_total_process_cost_cleaner");
        f55328a.add("iesve_processor_effect_process_cost_cleaner");
        f55328a.add("iesve_processor_frame_count_eq");
        f55328a.add("iesve_processor_sample_size_eq");
        f55328a.add("iesve_processor_total_process_cost_eq");
        f55328a.add("iesve_processor_effect_process_cost_eq");
        f55328a.add("iesve_processor_frame_count_reverb");
        f55328a.add("iesve_processor_sample_size_reverb");
        f55328a.add("iesve_processor_total_process_cost_reverb");
        f55328a.add("iesve_processor_effect_process_cost_reverb");
        f55328a.add("iesve_processor_frame_count_reverb2");
        f55328a.add("iesve_processor_sample_size_reverb2");
        f55328a.add("iesve_processor_total_process_cost_reverb2");
        f55328a.add("iesve_processor_effect_process_cost_reverb2");
        f55328a.add("iesve_processor_frame_count_volume");
        f55328a.add("iesve_processor_sample_size_volume");
        f55328a.add("iesve_processor_total_process_cost_volume");
        f55328a.add("iesve_processor_effect_process_cost_volume");
        f55328a.add("iesve_processor_frame_count_limiter");
        f55328a.add("iesve_processor_sample_size_limiter");
        f55328a.add("iesve_processor_processor_total_process_cost_limiter");
        f55328a.add("iesve_effect_process_cost_limiter");
    }

    /* renamed from: a */
    public static int m49668a(String str) {
        if (f55328a.contains(str)) {
            return 1;
        }
        if (f55331d.contains(str)) {
            return 3;
        }
        if (f55329b.contains(str)) {
            return 2;
        }
        return 0;
    }
}
