package com.bytedance.android.livesdk.config;

import com.bytedance.android.live.core.setting.C4097p;
import com.bytedance.android.livesdk.chatroom.model.C5762q;
import com.bytedance.android.livesdk.chatroom.model.C5763r;
import com.bytedance.android.livesdk.gift.effect.normal.view.NormalGiftView;
import com.bytedance.android.livesdk.gift.panel.p380a.C7524a;
import com.bytedance.android.livesdk.live.model.C7760d;
import com.bytedance.android.livesdk.p300c.C4961a;
import com.bytedance.android.livesdk.p385j.p387b.C7705a;
import com.bytedance.android.livesdkapi.p455i.C8809a;
import com.bytedance.android.livesdkapi.p455i.C8811b;
import com.bytedance.android.livesdkapi.p455i.C8813c;
import com.bytedance.android.livesdkapi.p455i.C8819i;
import com.bytedance.android.livesdkapi.p455i.C8820j;
import com.bytedance.android.livesdkapi.p455i.C8822k;
import com.bytedance.android.livesdkapi.p455i.C8823l;
import com.bytedance.android.livesdkapi.p455i.C8826o;
import com.p683ss.android.ugc.aweme.commercialize.abtest.NormalSplashDelayExperiment;
import java.util.ArrayList;
import java.util.List;

public interface LiveSettingKeys {
    public static final C4097p<C4961a> ASSET_ANIM_ID_MAP = new C4097p<>("webcast_asset_anim_id_map", "动态下发的特效ID的集合", new C4961a(), new C4961a());
    public static final C4097p<C8822k> AWEME_HOUR_RANK_ENTRANCE_STYLE;
    public static final C4097p<Integer> BAN_BARRAGE_SWITCH_SET = new C4097p<>("player_fullscreen_danmuku_enable", Integer.valueOf(1), "弹幕设置禁止");
    public static final C4097p<Boolean> CHI_JI_IS_OPEN = new C4097p<>("chiji_is_open", "是否吃鸡赛", Boolean.valueOf(false), Boolean.valueOf(true));
    public static final C4097p<Integer> COMMENT_PROMOTION_DELAY = new C4097p<>("comment_promotion_delay", Integer.valueOf(0), "进直播间几秒之后出现评论引导");
    public static final C4097p<Integer> DISABLE_ROOM_STICKER_NEW_BACK = new C4097p<>("disable_room_sticker_new_back", Integer.valueOf(0), "贴纸平台选择", "0:使用新平台", "1:使用老平台");
    public static final C4097p<Integer> DNS_OPT_METHOD = new C4097p<>("dns_opt_method", Integer.valueOf(0), "是否使用节点优选", "0:老版本", "1:新版本");
    public static final C4097p<Integer> DOUYIN_LIVE_FEED_TOP_HINT = new C4097p<>("live_squre_sky_window_info", Integer.valueOf(0), "抖音直播广场天窗关注文案AB");
    public static final String EMPTY_STRING = "";
    public static final C4097p<Boolean> ENABLE_ASSETS_DELETE_TIME_LIMIT = new C4097p<>("enable_assets_delete_time_limit", Boolean.valueOf(true), "是否开启资源删除的频控", "true:开启", "false:不开启");
    public static final C4097p<Boolean> ENABLE_COMMENT_BIND_PHONE = new C4097p<>("chat_need_bind_phone", Boolean.valueOf(false), "发评论是否需要绑定手机号", "false:不需要绑定", "true:需要绑定");
    public static final C4097p<Boolean> ENABLE_ENTER_ROOM_OPT_FROM_LIVE_AUDIENCE_END = new C4097p<>("enable_enter_room_opt_from_live_audience_end", "是否开启进房优化-观众直播结束页", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Boolean> ENABLE_ENTER_ROOM_OPT_REUSE_ROOM_PLAYER = new C4097p<>("enable_enter_room_opt_reuse_room_player", "是否开启进房优化二期-共享播放器", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Boolean> ENABLE_FANSCLUB_SEND_GIFT = new C4097p<>("show_fansclub_send_gift", Boolean.valueOf(false), "粉丝团吸底消息点击是否触发送礼", "false:不触发送礼", "true:触发送礼");
    public static final C4097p<Integer> ENABLE_FISSION_INVITE = new C4097p<>("enable_fission_invite", Integer.valueOf(0), "Vigo邀好友送钻石控制开关", "0:关闭", "1:打开");
    public static final C4097p<Boolean> ENABLE_FLOW_CARD_TIP_NEW_STYLE = new C4097p<>("enable_flow_card_tip_new_style", "抖音免流卡提示新策略", Boolean.valueOf(false), Boolean.valueOf(true));
    public static final C4097p<Boolean> ENABLE_LIVE_HTTPK_DEGRADE = new C4097p<>("live_httpk_degrade_enabled", "是否打开httpk降级开关", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> ENABLE_LIVE_TEXT_SCROLL_OPTIMIZE = new C4097p<>("enable_live_text_scroll_optimize", "是否开启评论区滑动速度优化", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Boolean> ENABLE_LOAD_POKEMON = new C4097p<>("enable_load_pokemon", Boolean.valueOf(false), "是否加载神奇宝贝widget", "false:不加载", "true:加载");
    public static final C4097p<Integer> ENABLE_READ_FROM_ASSETS = new C4097p<>("enable_read_from_assets", Integer.valueOf(0), "是否支持effesdk直接读取assets:0-否；1-是");
    public static final C4097p<Boolean> ENABLE_REFRESH_FORU_AVATAR_LIVE_STATUS = new C4097p<>("enable_refresh_foru_avatar_live_status", "foryou直播feed是否进行直播状态优化", Boolean.valueOf(false), Boolean.valueOf(true));
    public static final C4097p<Boolean> ENABLE_SINGLE_LOOPER_PLAYER_PULL_STREAM = new C4097p<>("enable_single_looper_player_pull_stream", "是否开启单looper播放器拉流", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> ENABLE_SLIDE_ENTER_ROOM_OPT = new C4097p<>("enable_slide_enter_room_opt", "启用上下滑进房优化", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> ENABLE_SLIDE_FROM_DAILY_RANK_FEED_DRAWER = new C4097p<>("live_enable_ranklist_slide_with_roomids_feed_drawer", "改版一直播间从小时榜跳转时是否支持小时榜上下滑", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> ENABLE_SLIDE_FROM_DAILY_RANK_NORMAL = new C4097p<>("live_enable_ranklist_slide_with_roomids", "常规直播间从小时榜跳转时是否支持上下滑", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> ENABLE_SLIDE_VIDEO_LAST_FRAME = new C4097p<>("enable_slide_video_last_frame", "启用上下滑进房优化，最后一帧优化", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> ENABLE_TOAST_NETWORK_CHANGED = new C4097p<>("enable_toast_network_changed", "西瓜头条是否显示网络环境改变的提示", Boolean.valueOf(false), Boolean.valueOf(true));
    public static final C4097p<Integer> FAST_GIFT_STYLE = new C4097p<>("fast_gift_style", "西瓜和头条快捷礼物样式", Integer.valueOf(1), Integer.valueOf(1));
    public static final C4097p<Integer> FAST_GIFT_TIME = new C4097p<>("fast_gift_time", Integer.valueOf(60), "进入直播间后多久显示首充动画");
    public static final C4097p<Boolean> FOLLOW_LIVE_CARD_STYLE = new C4097p<>("live_style", "关注Tab直播卡片样式", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> GAME_INTERACT_STYLE = new C4097p<>("live_enable_new_panel_banner", "西瓜直播间底部改版", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> GIFT_GUIDE_SHOW_ANCHOR_NAME = new C4097p<>("gift_guide_show_anchor_name", "送礼引导title展示的主播昵称", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Integer> HAS_TASK_RED_PACKET = new C4097p<>("has_task_red_packet", "D项目任务红包是否开始，这里只是个粗略的时间过滤", Integer.valueOf(1), Integer.valueOf(1));
    public static final C4097p<Boolean> HIDE_CHARGE_ICON_FOR_USER = new C4097p<>("hide_charge_icon_for_user", "是否隐藏充值按钮", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> HIDE_GIFT_ICON_FOR_USER = new C4097p<>("hide_gift_icon_for_user", "是否隐藏礼物面板", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> HOTSOON_LIVE_PK_LIVE_INVITE_RECOMMEND = new C4097p<>("pk_invite_recommend", "PK邀请列表优化为互关和推荐", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Integer> HOTSOON_PK_OPTIMIZE_USE_RIVAL = new C4097p<>("hotsoon_pk_optimize_use_rival", "火山控制邀请列表是否展示地理位置", Integer.valueOf(0), Integer.valueOf(1));
    public static final C4097p<Integer> HOT_LIVE_MESSAGE_SIZE = new C4097p<>("hot_live_message_size", "高热直播间消息数", Integer.valueOf(80), Integer.valueOf(80));
    public static final C4097p<String> I18N_ASSET_AUTHORIZE_URL = new C4097p<>("live_anchor_privacy_page_url", "", "vigo直播素材授权H5");
    public static final C4097p<String[]> I18N_SHARE_CHANNEL_LIST = new C4097p<>("live_share_channel_list_i18n", new String[]{"facebook", "twitter"}, "国际化直播分享方式");
    public static final C4097p<Boolean> I18N_SHOW_DAILY_RANK = new C4097p<>("i18n_show_daily_rank", Boolean.valueOf(false), "vigo是否显示小时榜更新逻辑", "false:不显示", "true:显示");
    public static final C4097p<Boolean> IS_LOAD_GIFT_RESOURCE_AFTER_FIRST_FRAME = new C4097p<>("is_load_gift_resource_after_first_frame", "是否在首帧后再加载礼物资源", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> LIVE_ANCHOR_INFO_ABTEST = new C4097p<>("live_anchor_info_abtest", Integer.valueOf(0), "主播个人信息widget显示信息");
    public static final C4097p<C7705a> LIVE_BEAUTY_PARAM = new C4097p<>("live_beauty_param", "直播美颜默认值及阈值设置", new C7705a(), new C7705a());
    public static final C4097p<Integer> LIVE_BEAUTY_TYPE_2;
    public static final C4097p<Boolean> LIVE_COMMENT_MESSAGE_BADGE_V2_ENABLE = new C4097p<>("live_comment_message_badge_v2_enable", "评论区勋章数量以及顺序使用server下发", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Integer> LIVE_COVER_MIN_SIZE = new C4097p<>("live_cover_min_size", "下发封面剪裁的最小值", Integer.valueOf(NormalSplashDelayExperiment.GROUP1), Integer.valueOf(NormalSplashDelayExperiment.GROUP1));
    public static final C4097p<Integer> LIVE_DAILY_RANK = new C4097p<>("hourly_rank_enable", Integer.valueOf(0), "小时榜相关tab展示类型");
    public static final C4097p<Integer> LIVE_DISABLE_DOWNLOAD_EFFECT_AT_APP_LAUNCH = new C4097p<>("live_disable_download_effect_at_app_launch", "是否禁止冷启后加载资源", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Boolean> LIVE_DISABLE_WEBVIEW_FILE_URI_MT = new C4097p<>("live_disable_webview_file_uri_mt", "是否禁止WebView的file协议", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Integer> LIVE_DOODLE_TEMPLATE_ENABLE = new C4097p<>("live_doodle_template_enable", "是否支持涂鸦模板, 0线上,1新涂鸦面板,2新面板+涂鸦模板", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Boolean> LIVE_DOUYIN_ENABLE_FIRST_CHARGE_V2 = new C4097p<>("douyin_first_charge_v2_enable", "抖音首充引导是否用新版", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Integer> LIVE_ENABLE_GUARD = new C4097p<>("live_enable_guard", Integer.valueOf(0), "是否开启守护入口", "0:关闭", "1:打开");
    public static final C4097p<Boolean> LIVE_ENABLE_NEW_GESTURE_DIALOG;
    public static final C4097p<Boolean> LIVE_ENABLE_NORMAL_GIFT_AND_BARRAGE_SELF_FIRSTLY = new C4097p<>("live_enable_normal_gift_and_barrage_self_firstly", "是否开启小礼物和弹幕自见优先", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> LIVE_ENABLE_TT_CAPTURE = new C4097p<>("enable_tt_capture", Integer.valueOf(1), "开启自研录屏推流", "0:不开启", "1:开启");
    public static final C4097p<Integer> LIVE_ENTER_DELAY_SHOW_LOADING_TIME = new C4097p<>("live_enter_delay_show_loading_time", "上下滑进入直播间延迟loading展现时机，弱化loading", Integer.valueOf(200), Integer.valueOf(200));
    public static final C4097p<Long> LIVE_FACE_STICKER_EFFECTIVELY_USE_TIME = new C4097p<>("live_face_sticker_effectively_use_time", Long.valueOf(30), "贴纸使用行为的统计时长");
    public static final C4097p<Integer> LIVE_FANS_CLUB_ENTRY_PLAN;
    public static final C4097p<String> LIVE_FANS_GROUP_URL = new C4097p<>("live_fans_group_url", "抖音体验优化粉丝团新样式", "", "");
    public static final C4097p<String> LIVE_FANS_PAGE_URL = new C4097p<>("live_fans_page_url", "粉丝团入口url", "https:/webcast.tiktokv.com/falcon/webcast_douyin/page/fansclub/index.html", "https://webcast.tiktokv.com/falcon/webcast_douyin/page/fansclub/index.html");
    public static final C4097p<Integer> LIVE_FAST_GIFT_COMBO_STYLE;
    public static final C4097p<Long> LIVE_FILTER_EFFECTIVELY_USE_TIME = new C4097p<>("live_filter_effectively_use_time", Long.valueOf(30), "滤镜使用行为的统计时长");
    public static final C4097p<C8809a> LIVE_FIRST_CHARGE_REWARD_PACKAGE;
    public static final C4097p<C8811b> LIVE_FIRST_CHARGE_REWARD_PACKAGE_V2;
    public static final C4097p<C8813c> LIVE_FIRST_CHARGE_TIP_INFO;
    public static final C4097p<C8819i> LIVE_GIFT_CHAIN_LENTH;
    public static final C4097p<Integer> LIVE_GIFT_DIALOG_STYLE;
    public static final C4097p<Integer> LIVE_GIFT_GUIDE_DELAY_TIME = new C4097p<>("live_gift_guide_delay_time", Integer.valueOf(NormalGiftView.ALPHA_180), "直播间送礼提醒delay时长", "3:默认时间");
    public static final C4097p<Integer> LIVE_GIFT_ICON_DOWNLOAD_MAX_FAIL = new C4097p<>("live_gift_icon_download_max_fail", "礼物小图标下载时允许的最大连续失败数", Integer.valueOf(4), Integer.valueOf(3));
    public static final C4097p<C7524a> LIVE_GIFT_PANEL_BANNER_LIST;
    public static final C4097p<Integer> LIVE_GIFT_PANEL_BG_STYLE = new C4097p<>("live_gift_panel_bg_style", "mt默认使用黑色礼物面板 0，使用白色面板 1", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Integer> LIVE_GIFT_PLAYER_USE_TYPE;
    public static final C4097p<Integer> LIVE_GIFT_RESOURCE_DOWNLOAD_MODE = new C4097p<>("live_gift_resource_download_mode", Integer.valueOf(2), "礼物资源的下载模式", "0:默认模式", "1:非断点续传模式", "2:使用TTDownloader模式");
    public static final C4097p<String> LIVE_GROUP_TOOLBAR_RED_DOT_SETTING = new C4097p<>("live_group_toolbar_reddot", "主播ToolBar红点展示动态配置", "", "");
    public static final C4097p<Integer> LIVE_HARDWARD_DECODE_H264_ENABLE = new C4097p<>("live_hardware_decode_h264_enable", Integer.valueOf(0), "264硬解开关", "1:打开", "0:关闭");
    public static final C4097p<Integer> LIVE_HARDWARD_DECODE_H265_ENABLE = new C4097p<>("live_hardware_decode_h265_enable", Integer.valueOf(0), "265硬解开关", "1:打开", "0:关闭");
    public static final C4097p<C8820j> LIVE_HONOR_LEVEL_SETTINGS_SETTING_KEY;
    public static final C4097p<Integer> LIVE_HOUR_RANK_REWARD_EXPORT = new C4097p<>("webcast_hour_rank_reward_export", "小时榜奖励出口 0为对照组，1为top3,2为top10", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Boolean> LIVE_IS_LOAD_GIFT_AFTER_FEED_END = new C4097p<>("live_is_load_gift_after_feed_end", "是否在直播Feed首刷后再加载资源", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> LIVE_LUCKY_BOX_TO_EXPIRE = new C4097p<>("live_lucky_box_to_expire", "宝箱可领取之后的有效期", Integer.valueOf(10), Integer.valueOf(10));
    public static final C4097p<Integer> LIVE_LUCKY_BOX_TO_SHOW = new C4097p<>("live_lucky_box_to_show", "宝箱显示倒计时的剩余秒数", Integer.valueOf(10), Integer.valueOf(10));
    public static final C4097p<String> LIVE_LUCKY_BOX_URL = new C4097p<>("live_lucky_box_url", "宝箱可领取之后的H5", "", "");
    public static final C4097p<Boolean> LIVE_MEET_ENVELOPE_ENABLE = new C4097p<>("live_meet_envelope_enabled", "", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Integer> LIVE_MESSAGE_QUEUE_MAX_LENGTH = new C4097p<>("live_message_queue_max_length", Integer.valueOf(200), "直播间礼物消息队列最大长度", "5:测试长度");
    public static final C4097p<Boolean> LIVE_MT_FEED_DRAWER_SHOW_MORE_LIVE = new C4097p<>("live_mt_feed_drawer_show_more_live", "直播间是否展示 更多直播drawer 开关", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> LIVE_MT_FORYOU_ENTRANCE_SHOW_MORE_LIVE = new C4097p<>("live_mt_foryou_entrance_show_more_live", "MT首页进入全屏直播，直播间抽屉入口控制", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> LIVE_MT_GUEST_LINK_ENABLE_GUEST_CONTRIBUTION_LIST = new C4097p<>("live_mt_guest_link_enable_guest_contribution_list", "MT嘉宾连麦是否开启榜单入口 true：开启，默认不开启", Boolean.valueOf(false), Boolean.valueOf(true));
    public static final C4097p<String> LIVE_MT_LOW_AGE_ANCHOR_LIMIT = new C4097p<>("low_age_anchor_limit", "mt低龄主播年限", "18", "18");
    public static final C4097p<String> LIVE_MT_LOW_AGE_AUDIENCE_LINKMIC_LIMIT = new C4097p<>("mt_low_age_audience_linkmic_limit", "mt嘉宾连麦低龄限制", "16", "16");
    public static final C4097p<String> LIVE_MT_LOW_AGE_REPORT_URL = new C4097p<>("live_sdk_appeal_webview", "mt低龄申诉引导url", "", "");
    public static final C4097p<String> LIVE_MT_LOW_AGE_USER_LIMIT = new C4097p<>("low_age_user_limit", "mt低龄用户年限", "18", "18");
    public static final C4097p<Boolean> LIVE_MT_NOTIFICATION_AB = new C4097p<>("live_enable_push_setting", "是否开启简介页小铃铛", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> LIVE_MT_USER_CAN_RECHARGE = new C4097p<>("can_recharge", "mt用户是否可以充值", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Boolean> LIVE_NET_ADAPTIVE_ENABLE = new C4097p<>("live_net_adaptive_enable", Boolean.valueOf(false), "是否开启网络自适应", "true:开启", "false:不开启");
    public static final C4097p<Float> LIVE_NET_ADAPTIVE_HURRY_SPEED = new C4097p<>("live_net_adaptive_hurry_speed", Float.valueOf(1.0f), "网络自适应追帧速度");
    public static final C4097p<Integer> LIVE_NET_ADAPTIVE_HURRY_TIME = new C4097p<>("live_net_adaptive_hurry_time", Integer.valueOf(2000), "开始追帧缓存阈值");
    public static final C4097p<Float> LIVE_NET_ADAPTIVE_SLOW_SPEED = new C4097p<>("live_net_adaptive_slow_speed", Float.valueOf(1.0f), "慢放速度");
    public static final C4097p<Integer> LIVE_NET_ADAPTIVE_SLOW_TIME = new C4097p<>("live_net_adaptive_slow_time", Integer.valueOf(0), "慢放阈值");
    public static final C4097p<Integer> LIVE_NEW_FEED_FIRST_FRAME_OPTIMIZE = new C4097p<>("live_new_feed_first_frame_op", "抖音方案一首帧优化ab控制", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Integer> LIVE_OPTIMIZE_STYLE_V1 = new C4097p<>("live_optimize_style_v1", "抖音方案一优化ab控制", Integer.valueOf(1), Integer.valueOf(1));
    public static final C4097p<Boolean> LIVE_PACKAKGE_PURCHASE = new C4097p<>("has_prop_bundle", Boolean.valueOf(false), "是否请求购买礼包接口", "false:不请求", "true:请求");
    public static final C4097p<Boolean> LIVE_PAGE_SHOW_BANNER = new C4097p<>("live_page_show_banner", Boolean.valueOf(false), "开播页是否展示banner", "true:显示", "false:不显示");
    public static final C4097p<Integer> LIVE_PROFILE_MANAGE_DIALOG_STYLE;
    public static final C4097p<Boolean> LIVE_RADIO_INTERACT_ENABLE = new C4097p<>("live_radio_interact_enable", Boolean.valueOf(false), "语音直播间是否显示连麦开关", "true:显示", "false:不显示");
    public static final C4097p<C5762q> LIVE_RANK_ANCHOR_CONFIG = new C4097p<>("live_rank_anchor_config", C5762q.class, "主播小时榜相关配置");
    public static final C4097p<C5763r> LIVE_RANK_CONFIG = new C4097p<>("live_rank_config", C5763r.class, "小时榜相关配置");
    public static final C4097p<C8826o> LIVE_RANK_INFO_LIST;
    public static final C4097p<Integer> LIVE_RECHARGE_DEFAULT_DEAL = new C4097p<>("live_recharge_default_deal", Integer.valueOf(0), "火山充值半屏是否默认选中套餐", "0:不默认选套餐", "1:默认选套餐");
    public static final C4097p<Integer> LIVE_RECHARGE_DIALOG_TYPE = new C4097p<>("live_douyin_recharge_dialog_type", Integer.valueOf(0), "直播间RechargeDialog弹出方式", "0:native dialog", "1:h5");
    public static final int LIVE_RECHARGE_DIALOG_TYPE_H5 = 1;
    public static final int LIVE_RECHARGE_DIALOG_TYPE_NATIVE = 0;
    public static final C4097p<Integer> LIVE_RECHARGE_HALF_DIALOG_UI = new C4097p<>("live_recharge_half_dialog_ui", Integer.valueOf(0), "火山充值半屏UIAB", "0:老UI", "1:新UI");
    public static final C4097p<Integer> LIVE_ROOM_CHARGE_TYPE = new C4097p<>("live_room_charge_type", Integer.valueOf(1), "充值弹窗 or 跳转页面");
    public static final int LIVE_ROOM_CHARGE_TYPE_ALERT_DIALOG = 0;
    public static final int LIVE_ROOM_CHARGE_TYPE_CHARGE_DIALOG = 1;
    public static final C4097p<Boolean> LIVE_SCREEN_SHOT_RECORD_ENABLE = new C4097p<>("live_screen_record_enable", "直播间截屏监控", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Integer> LIVE_SDK_FAST_OPEN_DISABLE = new C4097p<>("live_sdk_fast_open_disable", "是否关闭拉流首帧优化", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Boolean> LIVE_SDK_NEW_EFFECT_PLAYER = new C4097p<>("live_sdk_new_effect_player", "特效消息是否采用新优先级队列", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Boolean> LIVE_SDK_NOBLE_INTRODUCE_SHOW_ANDROID = new C4097p<>("live_sdk_noble_introduce_show_android", "西瓜贵族体系Android开关", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> LIVE_SDK_NTP_ENABLE = new C4097p<>("live_sdk_ntp_enable", "是否开启拉流NTP", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Integer> LIVE_SHARE_GET_DIAMONDS_TIME = new C4097p<>("live_share_get_diamonds_time", Integer.valueOf(NormalGiftView.ALPHA_180), "分享得钻石气泡等待展示时间");
    public static final C4097p<Boolean> LIVE_SHARE_LEAD_INNER = new C4097p<>("live_share_lead_inner", "直播间内分享引导", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> LIVE_SHARE_LEAD_OUTTER = new C4097p<>("live_share_lead_outter", "开播页分享引导", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> LIVE_SHARE_LEAD_SHOW = new C4097p<>("live_share_lead_show", "直播间提示语展示时延", Integer.valueOf(60000), Integer.valueOf(60000));
    public static final C4097p<Boolean> LIVE_SHOW_FANS_CLUB_RENEWAL = new C4097p<>("show_fansclub_renewal", Boolean.valueOf(false), "粉丝团自动点亮", "false: 没有入口", "true: 有入口");
    public static final C4097p<Boolean> LIVE_SHOW_GAME_QUIZ = new C4097p<>("live_show_game_quiz", Boolean.valueOf(false), " 是否显示游戏竞猜按钮");
    public static final C4097p<Integer> LIVE_SMALL_BEAUTY_AB_GROUP = new C4097p<>("live_small_beauty_ab_group", Integer.valueOf(0), "直播小项AB分组");
    public static final C4097p<Boolean> LIVE_START_BROADCAST_COVER = new C4097p<>("live_mt_cover_abtest", "开始直播界面是否可以上传封面", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<C7760d> LIVE_SWITCH_TO_SQUARE_TAB = new C4097p<>("close_live_switch_square_param", C7760d.class, "退出直播间跳宿主直播广场参数");
    public static final C4097p<Integer> LIVE_TEXT_WIDGET_SCROLL_SPEED = new C4097p<>("live_text_widget_scroll_speed", "设置评论区默认滑动速度", Integer.valueOf(600), Integer.valueOf(600));
    public static final C4097p<Integer> LIVE_TEXT_WIDGET_SHOW_MSG_PER_MILLIS = new C4097p<>("live_text_widget_show_msg_per_millis", "设置评论区每次更新时间间隔（单位ms）", Integer.valueOf(1000), Integer.valueOf(1000));
    public static final C4097p<Integer> LIVE_TEXT_WIDGET_SHOW_MSG_PER_SIZE = new C4097p<>("live_text_widget_show_msg_per_size", "设置评论区每次显示最大条数", Integer.valueOf(100), Integer.valueOf(100));
    public static final C4097p<C8823l> LIVE_TURNTABLE_CONFIG;
    public static final C4097p<Boolean> LIVE_USERNAME_DISPLAY = new C4097p<>("live_username_display", "直播展示Username", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> LIVE_USER_RANK = new C4097p<>("room_rank_enable", Integer.valueOf(1), "本场榜相关tab展示类型");
    public static final C4097p<Integer> LIVE_USE_NEW_AUDIO_CODEC;
    public static final C4097p<Boolean> LIVE_USE_NEW_GIFT_DIALOG;
    public static final C4097p<Boolean> LIVE_USE_PB_MESSAGE = new C4097p<>("live_use_pb_message", Boolean.valueOf(true), "直播消息使用 ProtoBuffers");
    public static final C4097p<Boolean> LIVE_VIEWPAGER_SLIDE_BLOCK_SWITCH = new C4097p<>("live_viewpager_slide_block_switch", "修复直播间viewpager卡顿的问题", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> LIVE_XIGUA_RANK = new C4097p<>("room_rank_xigua_enable", Integer.valueOf(0), "西瓜榜tab展示配置");
    public static final C4097p<Integer> MT_REFRESH_FORU_AVATAR_LIVE_STATE_INTERVAL = new C4097p<>("mt_refresh_foru_avatar_live_state_interval", "foryou直播feed直播状态刷新请求时间间隔", Integer.valueOf(60000), Integer.valueOf(60000));
    public static final C4097p<List<String>> NET_MONITOR_BLACK_LIST = new C4097p<>("net_monitor_black_list", "网络错误监控黑名单", new ArrayList(), new ArrayList());
    public static final C4097p<Integer> NEW_START_LIVE_STYLE = new C4097p<>("use_new_style_open_live", Integer.valueOf(0), "开播页样式");
    public static final C4097p<Boolean> OFFICIAL_CAN_GO_BACK = new C4097p<>("webcast_enable_project_d_official_room_go_back", "官方直播间支持跳转", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Integer> PK_RECOMMEND_AND_LINEKMIC_OPTMIZE = new C4097p<>("pk_recommend_and_linkmic_optimize", "抖音PK连线列表优化", Integer.valueOf(0), Integer.valueOf(1));
    public static final C4097p<Boolean> PLAYER_ENABLE_UPLOAD_TIME_LINE = new C4097p<>("player_enable_upload_time_line", Boolean.valueOf(false), "播放器时间序列开关");
    public static final C4097p<Boolean> SEND_GIFT_NOTFANS_DIALOG_ISOPEN = new C4097p<>("send_gift_notfans_dialog_isopen", "送粉丝团礼物时非粉丝团成员是否弹起引导加团弹窗", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<String[]> SHARE_CHANNEL_LIST = new C4097p<>("share_channel_list", new String[]{"分享 复制链接、保存 展现控制"});
    public static final C4097p<Integer> SHOW_ANCHOR_LEVEL = new C4097p<>("show_anchor_level", Integer.valueOf(0), "是否显示主播等级相关信息");
    public static final C4097p<Boolean> SHOW_BACKGROUND_BELOW_VIDEO = new C4097p<>("show_background_below_video", "是否展示底层背景", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> SHOW_EXCHANGE_SCORE = new C4097p<>("show_exchange_score", "VIGO是否展示火力换钻石", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Integer> SHOW_HUOLI_BUY_DIAMON = new C4097p<>("show_huoli_buy_diamond", "是否展示余额购买", Integer.valueOf(0), Integer.valueOf(1));
    public static final C4097p<Boolean> SHOW_PROP_PACKET = new C4097p<>("show_prop_packet", "西瓜和头条是否显示背包", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Integer> SLIDE_UP_SHOW_AB = new C4097p<>("live_guide_show_time", "是否进入直播间就展示上下滑引导", Integer.valueOf(0), Integer.valueOf(1));
    public static final C4097p<Integer> START_LIVE_SHARE_TIMEOUT = new C4097p<>("start_live_share_timeout", Integer.valueOf(5), "分享失败后直接开播");
    public static final C4097p<Integer> START_LIVE_STYLE = new C4097p<>("start_live_style_v2", Integer.valueOf(1), "开播页样式", "0:旧样式", "1:新样式");
    public static final C4097p<Integer> STREAM_DEFINITION_LEVEL = new C4097p<>("stream_definition_level", Integer.valueOf(0), "0线上 1普通、2高清");
    public static final C4097p<Integer> STREAM_HARDWARE_ENCODE = new C4097p<>("stream_hardware_encode", Integer.valueOf(0), "推流启动硬编码 0线上 1关闭 2开启");
    public static final C4097p<Integer> TTLIVE_PAY_TYPE = new C4097p<>("ttlive_pay_type", "收银台使用默认0, 使用财经 1", Integer.valueOf(0), Integer.valueOf(1));
    public static final C4097p<String> TURNTABLE_ICON_URL = new C4097p<>("turntable_icon_url", "转盘入口icon url", "", "");
    public static final C4097p<Integer> USE_NEW_RENDER_CHAIN = new C4097p<>("effect_sdk_use_new_render_chain", Integer.valueOf(1), "是否使用新的渲染链:0-不开启；1-开启");
    public static final C4097p<Integer> VIGO_FAST_GIFT_WAY = new C4097p<>("fast_gift_way", Integer.valueOf(0), "是否展示首充优化方案", "0:老方案", "1:新方案");
    public static final C4097p<Boolean> VIGO_FLAME_DIAMOND_GUIDE_SWITCH = new C4097p<>("vigo_flame_diamond_guide_switch", Boolean.valueOf(false), "是否展示火力引导", "true:显示；false:不显示");
    public static final C4097p<Integer> VIGO_SHARE_ROOM_DES_TYPE = new C4097p<>("vigo_share_room_des_type", Integer.valueOf(0), "vigo直播间分享文案ab", "0:原来的文案", "1:加emoji的文案");
    public static final C4097p<String> WEBVIEW_MONITOR_SLARDAR_SWITCH_SET = new C4097p<>("tt_live_webview_monitor_config_slardar_android", "WebView监控Slardar开关", "", "");
    public static final C4097p<Integer> WITH_DRAW_NEW_VERSION = new C4097p<>("with_draw_new_version", "新版提现", Integer.valueOf(0), Integer.valueOf(0));
    public static final C4097p<Boolean> XIGUA_LIVE_OPEN_QUIZ_FOR_ANCHOR = new C4097p<>("open_quiz_for_anchor", "西瓜游戏竞猜主播侧开关", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> XIGUA_LIVE_OPEN_QUIZ_FOR_USER = new C4097p<>("open_quiz_for_user", "西瓜游戏竞猜用户侧开关", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> XIGUA_LIVE_QUIZ_CLOSE_HIGH_BET = new C4097p<>("quiz_close_high_bet", "西瓜游戏高级竞猜是否关闭", Boolean.valueOf(false), Boolean.valueOf(false));
    public static final C4097p<Boolean> XT_DOODLE_GIFT_ENABLE = new C4097p<>("xt_doodle_gift_enable", "西瓜和头条是否开启涂鸦礼物", Boolean.valueOf(true), Boolean.valueOf(true));
    public static final C4097p<Boolean> XT_GAME_DOODLE_GIFT_ENABLE = new C4097p<>("xt_game_doodle_gift_enable", "西瓜和头条游戏直播间是否开启涂鸦礼物", Boolean.valueOf(false), Boolean.valueOf(false));

    static {
        C4097p pVar = new C4097p("live_use_qingyan2", "是否启用轻颜美颜2", Integer.valueOf(0), Integer.valueOf(1), "0:关闭", "1:开启");
        LIVE_BEAUTY_TYPE_2 = pVar;
        C4097p pVar2 = new C4097p("live_use_new_audio_codec", "推流音频是否使用high profile", Integer.valueOf(0), Integer.valueOf(1), "0:关闭", "1:开启");
        LIVE_USE_NEW_AUDIO_CODEC = pVar2;
        C4097p pVar3 = new C4097p("live_enable_new_gesture_dialog", "是否使用新交互手势面板", Boolean.valueOf(false), Boolean.valueOf(true), "true:开启新交互", "false:不开启新交互");
        LIVE_ENABLE_NEW_GESTURE_DIALOG = pVar3;
        C4097p pVar4 = new C4097p("first_charge", C8813c.class, "首充引导配置", null, null);
        LIVE_FIRST_CHARGE_TIP_INFO = pVar4;
        C4097p pVar5 = new C4097p("live_gift_dialog_style", "礼物面板送礼交互AB", Integer.valueOf(1), Integer.valueOf(0), "0:火山样式", "1:抖音样式");
        LIVE_GIFT_DIALOG_STYLE = pVar5;
        C4097p pVar6 = new C4097p("live_use_new_gift_dialog", "是否使用重构后的新礼物面板", Boolean.valueOf(true), Boolean.valueOf(true), "false:使用旧礼物面板", "true:使用新礼物面板");
        LIVE_USE_NEW_GIFT_DIALOG = pVar6;
        C4097p pVar7 = new C4097p("live_fast_gift_combo_style", "快捷礼物连发样式AB", Integer.valueOf(0), Integer.valueOf(0), "0:火山样式", "1:抖音样式");
        LIVE_FAST_GIFT_COMBO_STYLE = pVar7;
        C4097p pVar8 = new C4097p("live_fans_club_entry_style", "抖音粉丝团入口AB", Integer.valueOf(1), Integer.valueOf(1), "0:粉丝团入口在关注按钮点击的位置", "1:粉丝团入口在小时榜旁边");
        LIVE_FANS_CLUB_ENTRY_PLAN = pVar8;
        C4097p pVar9 = new C4097p("live_gift_panel_banner_list", C7524a.class, "礼物面板的banner数据", null, null);
        LIVE_GIFT_PANEL_BANNER_LIST = pVar9;
        C4097p pVar10 = new C4097p("ranklist_info", C8826o.class, "更多主播头像数据", null, null);
        LIVE_RANK_INFO_LIST = pVar10;
        C4097p pVar11 = new C4097p("live_first_recharge_upgrade_package", C8809a.class, "首充奖励配置", null, null);
        LIVE_FIRST_CHARGE_REWARD_PACKAGE = pVar11;
        C4097p pVar12 = new C4097p("live_first_recharge_upgrade_package_v2", C8811b.class, "VIGO首充奖励配置V2", null, null);
        LIVE_FIRST_CHARGE_REWARD_PACKAGE_V2 = pVar12;
        C4097p pVar13 = new C4097p("live_turntable_config", C8823l.class, "转盘入口相关配置", null, null);
        LIVE_TURNTABLE_CONFIG = pVar13;
        C4097p pVar14 = new C4097p("live_gift_chain_length", C8819i.class, (String) null, null, null);
        LIVE_GIFT_CHAIN_LENTH = pVar14;
        C4097p pVar15 = new C4097p("honor_level", C8820j.class, "荣誉等级settings", null, null);
        LIVE_HONOR_LEVEL_SETTINGS_SETTING_KEY = pVar15;
        C4097p pVar16 = new C4097p("live_gift_player_user_type", "视频礼物播放器降级策略", Integer.valueOf(0), Integer.valueOf(0), "0:强制使用TTPlayer", "1:优先使用MediaPlayer,异常自动回退使用TTPlayer", "2:强制使用MediaPlayer");
        LIVE_GIFT_PLAYER_USE_TYPE = pVar16;
        C4097p pVar17 = new C4097p("live_profile_manage_dialog_style", "直播间管理面板样式", Integer.valueOf(1), Integer.valueOf(1), "0:旧样式", "1:新样式");
        LIVE_PROFILE_MANAGE_DIALOG_STYLE = pVar17;
        C4097p pVar18 = new C4097p("live_rank_optimize_config", C8822k.class, "抖音小时榜外显样式", null, null);
        AWEME_HOUR_RANK_ENTRANCE_STYLE = pVar18;
    }
}
