package com.bytedance.android.live.base.model.proto;

import com.bytedance.android.livesdk.chatroom.model.C5710ac;
import com.bytedance.android.livesdk.chatroom.model.C5712ae;
import com.bytedance.android.livesdk.chatroom.model.C5713af;
import com.bytedance.android.livesdk.chatroom.model.C5714ag;
import com.bytedance.android.livesdk.chatroom.model.C5739ba;
import com.bytedance.android.livesdk.chatroom.model.C5740bb;
import com.bytedance.android.livesdk.chatroom.model.C5741bc;
import com.bytedance.android.livesdk.chatroom.model.C5742bd;
import com.bytedance.android.livesdk.chatroom.model.p323a.C5693c;
import com.bytedance.android.livesdk.chatroom.model.p323a.C5693c.C5694a;
import com.bytedance.android.livesdk.chatroom.model.p323a.C5704m;
import com.bytedance.android.livesdk.chatroom.model.p323a.C5705n;
import com.bytedance.android.livesdk.message.model.C7799af;
import com.bytedance.android.livesdk.message.model.C7799af.C7800a;
import com.bytedance.android.livesdk.message.model.C7801ag;
import com.bytedance.android.livesdk.message.model.C7803ai;
import com.bytedance.android.livesdk.message.model.C7807al;
import com.bytedance.android.livesdk.message.model.C7812aq;
import com.bytedance.android.livesdk.message.model.C7813ar;
import com.bytedance.android.livesdk.message.model.C7815at;
import com.bytedance.android.livesdk.message.model.C7816au;
import com.bytedance.android.livesdk.message.model.C7819ax;
import com.bytedance.android.livesdk.message.model.C7820ay;
import com.bytedance.android.livesdk.message.model.C7820ay.C7821a;
import com.bytedance.android.livesdk.message.model.C7820ay.C7821a.C7822a;
import com.bytedance.android.livesdk.message.model.C7823az;
import com.bytedance.android.livesdk.message.model.C7825ba;
import com.bytedance.android.livesdk.message.model.C7827bc;
import com.bytedance.android.livesdk.message.model.C7829bd;
import com.bytedance.android.livesdk.message.model.C7830be;
import com.bytedance.android.livesdk.message.model.C7831bf;
import com.bytedance.android.livesdk.message.model.C7832bg;
import com.bytedance.android.livesdk.message.model.C7833bh;
import com.bytedance.android.livesdk.message.model.C7834bi;
import com.bytedance.android.livesdk.message.model.C7837bk;
import com.bytedance.android.livesdk.message.model.C7848bq;
import com.bytedance.android.livesdk.message.model.C7849br;
import com.bytedance.android.livesdk.message.model.C7850bs;
import com.bytedance.android.livesdk.message.model.C7857bz;
import com.bytedance.android.livesdk.message.model.C7857bz.C7858a;
import com.bytedance.android.livesdk.message.model.C7862cc;
import com.bytedance.android.livesdk.message.model.C7863cd;
import com.bytedance.android.livesdk.message.model.C7864ce;
import com.bytedance.android.livesdk.message.model.C7865cf;
import com.bytedance.android.livesdk.message.model.C7866cg;
import com.bytedance.android.livesdk.message.model.C7867ch;
import com.bytedance.android.livesdk.message.model.C7868ci;
import com.bytedance.android.livesdk.message.model.C7869cj;
import com.bytedance.android.livesdk.message.model.C7871cl;
import com.bytedance.android.livesdk.message.model.C7874cn;
import com.bytedance.android.livesdk.message.model.C7875co;
import com.bytedance.android.livesdk.message.model.C7876cp;
import com.bytedance.android.livesdk.message.model.C7877cq;
import com.bytedance.android.livesdk.message.model.C7880cs;
import com.bytedance.android.livesdk.message.model.C7881ct;
import com.bytedance.android.livesdk.message.model.C7887cz;
import com.bytedance.android.livesdk.message.model.C7892dd;
import com.bytedance.android.livesdk.message.model.C7893de;
import com.bytedance.android.livesdk.message.model.C7896dh;
import com.bytedance.android.livesdk.message.model.C7899dk;
import com.bytedance.android.livesdk.message.model.C7900dl;
import com.bytedance.android.livesdk.message.model.C7901dm;
import com.bytedance.android.livesdk.message.model.C7904dp;
import com.bytedance.android.livesdk.message.model.C7905dq;
import com.bytedance.android.livesdk.message.model.C7907dr;
import com.bytedance.android.livesdk.message.model.C7908ds;
import com.bytedance.android.livesdk.message.model.C7914dx;
import com.bytedance.android.livesdk.message.model.C7915dy;
import com.bytedance.android.livesdk.message.model.C7916dz;
import com.bytedance.android.livesdk.message.model.C7918ea;
import com.bytedance.android.livesdk.message.model.C7920ec;
import com.bytedance.android.livesdk.message.model.C7924eg;
import com.bytedance.android.livesdk.message.model.C7928ek;
import com.bytedance.android.livesdk.message.model.C7929el;
import com.bytedance.android.livesdk.message.model.C7931en;
import com.bytedance.android.livesdk.message.model.C7932eo;
import com.bytedance.android.livesdk.message.model.C7934eq;
import com.bytedance.android.livesdk.message.model.C7935er;
import com.bytedance.android.livesdk.message.model.C7936es;
import com.bytedance.android.livesdk.message.model.C7937et;
import com.bytedance.android.livesdk.message.model.C7938eu;
import com.bytedance.android.livesdk.message.model.C7939ev;
import com.bytedance.android.livesdk.message.model.C7941ex;
import com.bytedance.android.livesdk.message.model.C7942ey;
import com.bytedance.android.livesdk.message.model.C7943ez;
import com.bytedance.android.livesdk.message.model.C7945fa;
import com.bytedance.android.livesdk.message.model.C7946fb;
import com.bytedance.android.livesdk.message.model.C7948fd;
import com.bytedance.android.livesdk.message.model.C7949fe;
import com.bytedance.android.livesdk.message.model.C7952fh;
import com.bytedance.android.livesdk.message.model.C7962fr;
import com.bytedance.android.livesdk.message.model.C7963fs;
import com.bytedance.android.livesdk.message.model.C7964ft;
import com.bytedance.android.livesdk.message.model.C7971g;
import com.bytedance.android.livesdk.message.model.C7972ga;
import com.bytedance.android.livesdk.message.model.C7973gb;
import com.bytedance.android.livesdk.message.model.C7975gd;
import com.bytedance.android.livesdk.message.model.C7976ge;
import com.bytedance.android.livesdk.message.model.C7977gf;
import com.bytedance.android.livesdk.message.model.C7978gg;
import com.bytedance.android.livesdk.message.model.C7979gh;
import com.bytedance.android.livesdk.message.model.C7980gi;
import com.bytedance.android.livesdk.message.model.C7981gj;
import com.bytedance.android.livesdk.message.model.C7982gk;
import com.bytedance.android.livesdk.message.model.C7983gl;
import com.bytedance.android.livesdk.message.model.C7984gm;
import com.bytedance.android.livesdk.message.model.C7985gn;
import com.bytedance.android.livesdk.message.model.C7988gq;
import com.bytedance.android.livesdk.message.model.C7989gr;
import com.bytedance.android.livesdk.message.model.C7990gs;
import com.bytedance.android.livesdk.message.model.C7991gt;
import com.bytedance.android.livesdk.message.model.C7994gw;
import com.bytedance.android.livesdk.message.model.C7995gx;
import com.bytedance.android.livesdk.message.model.C7999k;
import com.bytedance.android.livesdk.message.model.C8000l;
import com.bytedance.android.livesdk.message.model.C8003o;
import com.bytedance.android.livesdk.message.model.C8006q;
import com.bytedance.android.livesdk.message.model.C8007r;
import com.bytedance.android.livesdk.message.model.C8008s;
import com.bytedance.android.livesdk.message.model.C8011u;
import com.bytedance.android.livesdk.message.model.C8012v;
import com.bytedance.android.livesdk.message.model.C8014x;
import com.bytedance.android.livesdk.message.model.C8016y;
import com.bytedance.android.livesdk.message.model.FansclubStatisticMessage;
import com.bytedance.android.livesdk.message.model.RoomNotifyMessageExtra;
import com.bytedance.android.livesdk.message.model.RoomNotifyMessageExtra.Background;
import com.bytedance.android.p173d.p174a.p175a.C2888b;
import java.util.HashMap;
import java.util.Map;

/* renamed from: com.bytedance.android.live.base.model.proto.b */
public final class C2994b {

    /* renamed from: a */
    public static final Map<Class, C2888b> f8806a = new HashMap();

    static {
        new C2997e();
        C2997e.m8388a(f8806a);
        new _ProtoDecoders_LIVEBASE().inject(f8806a);
        new C2996d();
        Map<Class, C2888b> map = f8806a;
        map.put(C8012v.class, new C7905dq());
        map.put(C7999k.class, new C7892dd());
        map.put(C7829bd.class, new C7942ey());
        map.put(C7864ce.class, new C7977gf());
        map.put(C7819ax.class, new C7934eq());
        map.put(C7815at.class, new C7931en());
        map.put(C7862cc.class, new C7975gd());
        map.put(C7799af.class, new C7914dx());
        map.put(C7800a.class, new C7915dy());
        map.put(C8006q.class, new C7899dk());
        map.put(C7831bf.class, new C7945fa());
        map.put(C7880cs.class, new C7994gw());
        map.put(C7865cf.class, new C7980gi());
        map.put(C7820ay.class, new C7935er());
        map.put(C7821a.class, new C7936es());
        map.put(C7822a.class, new C7937et());
        map.put(C7869cj.class, new C7984gm());
        map.put(C8014x.class, new C7907dr());
        map.put(RoomNotifyMessageExtra.class, new C7979gh());
        map.put(Background.class, new C7978gg());
        map.put(C7867ch.class, new C7982gk());
        map.put(C8008s.class, new C7901dm());
        map.put(FansclubStatisticMessage.class, new C7918ea());
        map.put(C7807al.class, new C7924eg());
        map.put(C7803ai.class, new C7920ec());
        map.put(C7868ci.class, new C7983gl());
        map.put(C7849br.class, new C7963fs());
        map.put(C8000l.class, new C7893de());
        map.put(C7850bs.class, new C7964ft());
        map.put(C8011u.class, new C7904dp());
        map.put(C7832bg.class, new C7946fb());
        map.put(C8003o.class, new C7896dh());
        map.put(C7874cn.class, new C7988gq());
        map.put(C7837bk.class, new C7952fh());
        map.put(C7801ag.class, new C7916dz());
        map.put(C8007r.class, new C7900dl());
        map.put(C7881ct.class, new C7995gx());
        map.put(C7830be.class, new C7943ez());
        map.put(C7866cg.class, new C7981gj());
        map.put(C7863cd.class, new C7976ge());
        map.put(C8016y.class, new C7908ds());
        map.put(C7825ba.class, new C7939ev());
        map.put(C7876cp.class, new C7990gs());
        map.put(C7833bh.class, new C7948fd());
        map.put(C7971g.class, new C7887cz());
        map.put(C7813ar.class, new C7929el());
        map.put(C7823az.class, new C7938eu());
        map.put(C7827bc.class, new C7941ex());
        map.put(C7812aq.class, new C7928ek());
        map.put(C7871cl.class, new C7985gn());
        map.put(C7848bq.class, new C7962fr());
        map.put(C7834bi.class, new C7949fe());
        map.put(C7875co.class, new C7989gr());
        map.put(C7857bz.class, new C7972ga());
        map.put(C7858a.class, new C7973gb());
        map.put(C7877cq.class, new C7991gt());
        map.put(C7816au.class, new C7932eo());
        map.put(C5714ag.class, new C5742bd());
        map.put(C5710ac.class, new C5739ba());
        map.put(C5712ae.class, new C5740bb());
        map.put(C5713af.class, new C5741bc());
        map.put(C5693c.class, new C5704m());
        map.put(C5694a.class, new C5705n());
    }
}
