package com.bytedance.android.live.base.model.proto;

import com.bytedance.android.livesdk.chatroom.interact.p318g.C5382c;
import com.bytedance.android.livesdk.chatroom.interact.p318g.C5385e;
import com.bytedance.android.livesdk.chatroom.model.C5735ax;
import com.bytedance.android.livesdk.chatroom.model.C5736ay;
import com.bytedance.android.livesdk.chatroom.model.C5737az;
import com.bytedance.android.livesdk.chatroom.model.C5738b;
import com.bytedance.android.livesdk.chatroom.model.C5743c;
import com.bytedance.android.livesdk.chatroom.model.C5743c.C5744a;
import com.bytedance.android.livesdk.chatroom.model.p323a.C5703l;
import com.bytedance.android.livesdk.chatroom.model.p323a.C5706o;
import com.bytedance.android.livesdk.gift.relay.p381a.C7629a;
import com.bytedance.android.livesdk.gift.relay.p381a.C7633d;
import com.bytedance.android.livesdk.message.model.C7793a;
import com.bytedance.android.livesdk.message.model.C7796ac;
import com.bytedance.android.livesdk.message.model.C7797ad;
import com.bytedance.android.livesdk.message.model.C7798ae;
import com.bytedance.android.livesdk.message.model.C7802ah;
import com.bytedance.android.livesdk.message.model.C7804aj;
import com.bytedance.android.livesdk.message.model.C7805ak;
import com.bytedance.android.livesdk.message.model.C7805ak.C7806a;
import com.bytedance.android.livesdk.message.model.C7809an;
import com.bytedance.android.livesdk.message.model.C7810ao;
import com.bytedance.android.livesdk.message.model.C7811ap;
import com.bytedance.android.livesdk.message.model.C7814as;
import com.bytedance.android.livesdk.message.model.C7817av;
import com.bytedance.android.livesdk.message.model.C7824b;
import com.bytedance.android.livesdk.message.model.C7826bb;
import com.bytedance.android.livesdk.message.model.C7835bj;
import com.bytedance.android.livesdk.message.model.C7835bj.C7836a;
import com.bytedance.android.livesdk.message.model.C7838bl;
import com.bytedance.android.livesdk.message.model.C7839bm;
import com.bytedance.android.livesdk.message.model.C7840bn;
import com.bytedance.android.livesdk.message.model.C7841bo;
import com.bytedance.android.livesdk.message.model.C7841bo.C7842a;
import com.bytedance.android.livesdk.message.model.C7843bp;
import com.bytedance.android.livesdk.message.model.C7843bp.C7845b;
import com.bytedance.android.livesdk.message.model.C7843bp.C7846c;
import com.bytedance.android.livesdk.message.model.C7843bp.C7847d;
import com.bytedance.android.livesdk.message.model.C7851bt;
import com.bytedance.android.livesdk.message.model.C7852bu;
import com.bytedance.android.livesdk.message.model.C7853bv;
import com.bytedance.android.livesdk.message.model.C7854bw;
import com.bytedance.android.livesdk.message.model.C7855bx;
import com.bytedance.android.livesdk.message.model.C7860ca;
import com.bytedance.android.livesdk.message.model.C7861cb;
import com.bytedance.android.livesdk.message.model.C7872cm;
import com.bytedance.android.livesdk.message.model.C7872cm.C7873a;
import com.bytedance.android.livesdk.message.model.C7878cr;
import com.bytedance.android.livesdk.message.model.C7878cr.C7879a;
import com.bytedance.android.livesdk.message.model.C7882cu;
import com.bytedance.android.livesdk.message.model.C7883cv;
import com.bytedance.android.livesdk.message.model.C7884cw;
import com.bytedance.android.livesdk.message.model.C7885cx;
import com.bytedance.android.livesdk.message.model.C7886cy;
import com.bytedance.android.livesdk.message.model.C7888d;
import com.bytedance.android.livesdk.message.model.C7889da;
import com.bytedance.android.livesdk.message.model.C7890db;
import com.bytedance.android.livesdk.message.model.C7891dc;
import com.bytedance.android.livesdk.message.model.C7894df;
import com.bytedance.android.livesdk.message.model.C7895dg;
import com.bytedance.android.livesdk.message.model.C7897di;
import com.bytedance.android.livesdk.message.model.C7898dj;
import com.bytedance.android.livesdk.message.model.C7902dn;
import com.bytedance.android.livesdk.message.model.C7903do;
import com.bytedance.android.livesdk.message.model.C7909dt;
import com.bytedance.android.livesdk.message.model.C7911du;
import com.bytedance.android.livesdk.message.model.C7912dv;
import com.bytedance.android.livesdk.message.model.C7913dw;
import com.bytedance.android.livesdk.message.model.C7917e;
import com.bytedance.android.livesdk.message.model.C7919eb;
import com.bytedance.android.livesdk.message.model.C7921ed;
import com.bytedance.android.livesdk.message.model.C7922ee;
import com.bytedance.android.livesdk.message.model.C7923ef;
import com.bytedance.android.livesdk.message.model.C7925eh;
import com.bytedance.android.livesdk.message.model.C7926ei;
import com.bytedance.android.livesdk.message.model.C7927ej;
import com.bytedance.android.livesdk.message.model.C7930em;
import com.bytedance.android.livesdk.message.model.C7933ep;
import com.bytedance.android.livesdk.message.model.C7940ew;
import com.bytedance.android.livesdk.message.model.C7944f;
import com.bytedance.android.livesdk.message.model.C7947fc;
import com.bytedance.android.livesdk.message.model.C7950ff;
import com.bytedance.android.livesdk.message.model.C7951fg;
import com.bytedance.android.livesdk.message.model.C7953fi;
import com.bytedance.android.livesdk.message.model.C7954fj;
import com.bytedance.android.livesdk.message.model.C7955fk;
import com.bytedance.android.livesdk.message.model.C7956fl;
import com.bytedance.android.livesdk.message.model.C7957fm;
import com.bytedance.android.livesdk.message.model.C7958fn;
import com.bytedance.android.livesdk.message.model.C7959fo;
import com.bytedance.android.livesdk.message.model.C7960fp;
import com.bytedance.android.livesdk.message.model.C7961fq;
import com.bytedance.android.livesdk.message.model.C7965fu;
import com.bytedance.android.livesdk.message.model.C7966fv;
import com.bytedance.android.livesdk.message.model.C7967fw;
import com.bytedance.android.livesdk.message.model.C7968fx;
import com.bytedance.android.livesdk.message.model.C7969fy;
import com.bytedance.android.livesdk.message.model.C7970fz;
import com.bytedance.android.livesdk.message.model.C7974gc;
import com.bytedance.android.livesdk.message.model.C7986go;
import com.bytedance.android.livesdk.message.model.C7987gp;
import com.bytedance.android.livesdk.message.model.C7992gu;
import com.bytedance.android.livesdk.message.model.C7993gv;
import com.bytedance.android.livesdk.message.model.C7996h;
import com.bytedance.android.livesdk.message.model.C7997i;
import com.bytedance.android.livesdk.message.model.C7998j;
import com.bytedance.android.livesdk.message.model.C8001m;
import com.bytedance.android.livesdk.message.model.C8002n;
import com.bytedance.android.livesdk.message.model.C8004p;
import com.bytedance.android.livesdk.message.model.C8004p.C8005a;
import com.bytedance.android.livesdk.message.model.C8009t;
import com.bytedance.android.livesdk.message.model.C8009t.C8010a;
import com.bytedance.android.livesdk.message.model.C8017z;
import com.bytedance.android.livesdk.message.model.LotteryEventMessage;
import com.bytedance.android.p173d.p174a.p175a.C2888b;
import java.util.HashMap;
import java.util.Map;

/* renamed from: com.bytedance.android.live.base.model.proto.e */
public final class C2997e {

    /* renamed from: a */
    private static final Map<Class, C2888b> f8809a = new HashMap();

    /* renamed from: a */
    public static void m8388a(Map<Class, C2888b> map) {
        map.put(C5703l.class, new C5706o());
        map.put(C5738b.class, new C5735ax());
        map.put(C5743c.class, new C5737az());
        map.put(C5744a.class, new C5736ay());
        map.put(C5382c.class, new C5385e());
        map.put(C7797ad.class, new C7912dv());
        map.put(C7944f.class, new C7886cy());
        map.put(C7826bb.class, new C7940ew());
        map.put(C7855bx.class, new C7969fy());
        map.put(C7843bp.class, new C7961fq());
        map.put(C7845b.class, new C7958fn());
        map.put(C7847d.class, new C7960fp());
        map.put(C7846c.class, new C7959fo());
        map.put(C7793a.class, new C7882cu());
        map.put(C7888d.class, new C7884cw());
        map.put(C7804aj.class, new C7921ed());
        map.put(C7997i.class, new C7890db());
        map.put(C7796ac.class, new C7911du());
        map.put(C7861cb.class, new C7974gc());
        map.put(C7851bt.class, new C7965fu());
        map.put(C7817av.class, new C7933ep());
        map.put(C8002n.class, new C7895dg());
        map.put(C7917e.class, new C7885cx());
        map.put(C8004p.class, new C7898dj());
        map.put(C8005a.class, new C7897di());
        map.put(C7798ae.class, new C7913dw());
        map.put(C7838bl.class, new C7953fi());
        map.put(C7840bn.class, new C7955fk());
        map.put(C7824b.class, new C7883cv());
        map.put(C7839bm.class, new C7954fj());
        map.put(C7853bv.class, new C7968fx());
        map.put(C7810ao.class, new C7926ei());
        map.put(C7835bj.class, new C7951fg());
        map.put(C7836a.class, new C7950ff());
        map.put(C7996h.class, new C7889da());
        map.put(C7852bu.class, new C7966fv());
        map.put(C7878cr.class, new C7993gv());
        map.put(C7879a.class, new C7992gu());
        map.put(C8017z.class, new C7909dt());
        map.put(C7805ak.class, new C7923ef());
        map.put(C7806a.class, new C7922ee());
        map.put(C7998j.class, new C7891dc());
        map.put(LotteryEventMessage.class, new C7947fc());
        map.put(C7854bw.class, new C7967fw());
        map.put(C7809an.class, new C7925eh());
        map.put(C7841bo.class, new C7957fm());
        map.put(C7842a.class, new C7956fl());
        map.put(C7872cm.class, new C7987gp());
        map.put(C7873a.class, new C7986go());
        map.put(C7860ca.class, new C7970fz());
        map.put(C7802ah.class, new C7919eb());
        map.put(C7811ap.class, new C7927ej());
        map.put(C8001m.class, new C7894df());
        map.put(C8009t.class, new C7903do());
        map.put(C8010a.class, new C7902dn());
        map.put(C7814as.class, new C7930em());
        map.put(C7629a.class, new C7633d());
    }
}
