package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.C15237g;
import com.google.android.gms.common.api.C15237g.C15238a;
import com.google.android.gms.common.api.C15358j;
import com.google.android.gms.common.api.C15359k;
import com.google.android.gms.common.api.Status;

/* renamed from: com.google.android.gms.common.api.internal.bo */
public final class C15286bo<R extends C15358j> extends C15237g<R> {

    /* renamed from: a */
    public final Status f39449a;

    /* renamed from: a */
    public final void mo28121a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: b */
    public final boolean mo28124b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo28123a(C15359k<? super R> kVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo28122a(C15238a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: c */
    public final Integer mo28125c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
